export const features = [
  {
    id: 'foiarequests',
    name: 'FOIA Requests',
    icon: '📋',
    color: '#6366f1',
    description: 'Freedom of Information Act requests tracking and AI analysis',
    aiType: 'foia',
    columns: ['title', 'agency', 'status', 'priority', 'requestDate'],
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'agency', label: 'Agency', type: 'text', required: true },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'in_progress', 'completed', 'denied', 'appealed'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'urgent'] },
      { key: 'requestorName', label: 'Requestor Name', type: 'text' },
      { key: 'requestorEmail', label: 'Requestor Email', type: 'text' },
      { key: 'trackingNumber', label: 'Tracking Number', type: 'text' },
      { key: 'estimatedCost', label: 'Estimated Cost', type: 'number' },
      { key: 'category', label: 'Category', type: 'text' }
    ],
    aiFields: ['title', 'agency', 'description']
  },
  {
    id: 'titlesearches',
    name: 'Title Searches',
    icon: '🏠',
    color: '#10b981',
    description: 'Property title search records and ownership verification',
    aiType: 'title',
    columns: ['propertyAddress', 'county', 'state', 'titleStatus', 'ownerName'],
    fields: [
      { key: 'propertyAddress', label: 'Property Address', type: 'text', required: true },
      { key: 'county', label: 'County', type: 'text', required: true },
      { key: 'state', label: 'State', type: 'text', required: true },
      { key: 'ownerName', label: 'Owner Name', type: 'text' },
      { key: 'parcelNumber', label: 'Parcel Number', type: 'text' },
      { key: 'legalDescription', label: 'Legal Description', type: 'textarea' },
      { key: 'titleStatus', label: 'Title Status', type: 'select', options: ['clear', 'encumbered', 'pending', 'disputed'] },
      { key: 'assessedValue', label: 'Assessed Value', type: 'number' },
      { key: 'marketValue', label: 'Market Value', type: 'number' },
      { key: 'propertyType', label: 'Property Type', type: 'text' },
      { key: 'yearBuilt', label: 'Year Built', type: 'number' }
    ],
    aiFields: ['propertyAddress', 'county', 'state', 'ownerName']
  },
  {
    id: 'regulatoryfilings',
    name: 'Regulatory Filings',
    icon: '📑',
    color: '#f59e0b',
    description: 'Track regulatory submissions and compliance status',
    aiType: 'regulatory',
    columns: ['entityName', 'filingType', 'regulatoryBody', 'status', 'complianceScore'],
    fields: [
      { key: 'filingType', label: 'Filing Type', type: 'text', required: true },
      { key: 'entityName', label: 'Entity Name', type: 'text', required: true },
      { key: 'regulatoryBody', label: 'Regulatory Body', type: 'text', required: true },
      { key: 'filingNumber', label: 'Filing Number', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['submitted', 'under_review', 'approved', 'rejected', 'amended'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'industry', label: 'Industry', type: 'text' },
      { key: 'complianceScore', label: 'Compliance Score', type: 'number' },
      { key: 'penaltyAmount', label: 'Penalty Amount', type: 'number' }
    ],
    aiFields: ['filingType', 'entityName', 'regulatoryBody', 'description']
  },
  {
    id: 'courtrecords',
    name: 'Court Records',
    icon: '⚖️',
    color: '#ef4444',
    description: 'Court case records, litigation tracking, and case analysis',
    aiType: 'court',
    columns: ['caseNumber', 'caseTitle', 'court', 'caseType', 'status'],
    fields: [
      { key: 'caseNumber', label: 'Case Number', type: 'text', required: true },
      { key: 'caseTitle', label: 'Case Title', type: 'text', required: true },
      { key: 'court', label: 'Court', type: 'text', required: true },
      { key: 'judge', label: 'Judge', type: 'text' },
      { key: 'plaintiff', label: 'Plaintiff', type: 'text' },
      { key: 'defendant', label: 'Defendant', type: 'text' },
      { key: 'caseType', label: 'Case Type', type: 'select', options: ['civil', 'criminal', 'family', 'bankruptcy', 'appellate'] },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'closed', 'settled', 'dismissed', 'appealed'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'jurisdiction', label: 'Jurisdiction', type: 'text' },
      { key: 'damagesAmount', label: 'Damages Amount', type: 'number' }
    ],
    aiFields: ['caseTitle', 'court', 'caseType', 'plaintiff', 'defendant', 'description']
  },
  {
    id: 'propertyrecords',
    name: 'Property Records',
    icon: '🏢',
    color: '#06b6d4',
    description: 'Property ownership, assessments, and tax records',
    aiType: 'property',
    columns: ['address', 'city', 'state', 'propertyType', 'assessedValue'],
    fields: [
      { key: 'address', label: 'Address', type: 'text', required: true },
      { key: 'city', label: 'City', type: 'text', required: true },
      { key: 'state', label: 'State', type: 'text', required: true },
      { key: 'zipCode', label: 'ZIP Code', type: 'text' },
      { key: 'ownerName', label: 'Owner Name', type: 'text' },
      { key: 'propertyType', label: 'Property Type', type: 'select', options: ['residential', 'commercial', 'industrial', 'agricultural', 'vacant'] },
      { key: 'assessedValue', label: 'Assessed Value', type: 'number' },
      { key: 'marketValue', label: 'Market Value', type: 'number' },
      { key: 'taxAmount', label: 'Tax Amount', type: 'number' },
      { key: 'squareFeet', label: 'Square Feet', type: 'number' },
      { key: 'yearBuilt', label: 'Year Built', type: 'number' },
      { key: 'bedrooms', label: 'Bedrooms', type: 'number' },
      { key: 'bathrooms', label: 'Bathrooms', type: 'number' },
      { key: 'zoningCode', label: 'Zoning Code', type: 'text' }
    ],
    aiFields: ['address', 'city', 'state', 'propertyType', 'assessedValue', 'marketValue']
  },
  {
    id: 'businessfilings',
    name: 'Business Filings',
    icon: '🏛️',
    color: '#8b5cf6',
    description: 'Business entity registrations and corporate filings',
    aiType: 'business',
    columns: ['businessName', 'entityType', 'stateOfIncorporation', 'status', 'industry'],
    fields: [
      { key: 'businessName', label: 'Business Name', type: 'text', required: true },
      { key: 'entityType', label: 'Entity Type', type: 'select', options: ['LLC', 'Corporation', 'Partnership', 'Sole Proprietorship', 'Non-Profit'], required: true },
      { key: 'stateOfIncorporation', label: 'State', type: 'text', required: true },
      { key: 'filingNumber', label: 'Filing Number', type: 'text' },
      { key: 'registeredAgent', label: 'Registered Agent', type: 'text' },
      { key: 'principalAddress', label: 'Principal Address', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'dissolved', 'suspended', 'revoked'] },
      { key: 'industry', label: 'Industry', type: 'text' },
      { key: 'ein', label: 'EIN', type: 'text' }
    ],
    aiFields: ['businessName', 'entityType', 'stateOfIncorporation', 'industry']
  },
  {
    id: 'buildingpermits',
    name: 'Building Permits',
    icon: '🔨',
    color: '#f97316',
    description: 'Construction permits, inspections, and code compliance',
    aiType: 'permit',
    columns: ['permitNumber', 'propertyAddress', 'permitType', 'status', 'estimatedCost'],
    fields: [
      { key: 'permitNumber', label: 'Permit Number', type: 'text', required: true },
      { key: 'propertyAddress', label: 'Property Address', type: 'text', required: true },
      { key: 'permitType', label: 'Permit Type', type: 'select', options: ['new_construction', 'renovation', 'demolition', 'electrical', 'plumbing', 'mechanical'], required: true },
      { key: 'applicantName', label: 'Applicant Name', type: 'text' },
      { key: 'contractorName', label: 'Contractor Name', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['applied', 'approved', 'denied', 'expired', 'completed', 'inspection_pending'] },
      { key: 'estimatedCost', label: 'Estimated Cost', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'municipality', label: 'Municipality', type: 'text' }
    ],
    aiFields: ['permitType', 'propertyAddress', 'description', 'estimatedCost']
  },
  {
    id: 'vitalrecords',
    name: 'Vital Records',
    icon: '📜',
    color: '#ec4899',
    description: 'Birth, death, marriage, and divorce certificates',
    aiType: 'vital',
    columns: ['fullName', 'recordType', 'dateOfEvent', 'state', 'status'],
    fields: [
      { key: 'recordType', label: 'Record Type', type: 'select', options: ['birth', 'death', 'marriage', 'divorce'], required: true },
      { key: 'fullName', label: 'Full Name', type: 'text', required: true },
      { key: 'dateOfEvent', label: 'Date of Event', type: 'date', required: true },
      { key: 'county', label: 'County', type: 'text' },
      { key: 'state', label: 'State', type: 'text', required: true },
      { key: 'certificateNumber', label: 'Certificate Number', type: 'text' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['verified', 'pending', 'amended', 'sealed'] },
      { key: 'notes', label: 'Notes', type: 'textarea' }
    ],
    aiFields: ['recordType', 'fullName', 'state']
  },
  {
    id: 'taxliens',
    name: 'Tax Liens',
    icon: '💰',
    color: '#dc2626',
    description: 'Federal, state, and property tax lien records',
    aiType: 'taxlien',
    columns: ['lienNumber', 'debtorName', 'lienType', 'amount', 'status'],
    fields: [
      { key: 'lienNumber', label: 'Lien Number', type: 'text', required: true },
      { key: 'debtorName', label: 'Debtor Name', type: 'text', required: true },
      { key: 'lienType', label: 'Lien Type', type: 'select', options: ['federal', 'state', 'property', 'income', 'payroll'], required: true },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'released', 'subordinated', 'expired', 'paid'] },
      { key: 'propertyAddress', label: 'Property Address', type: 'text' },
      { key: 'jurisdiction', label: 'Jurisdiction', type: 'text' },
      { key: 'taxYear', label: 'Tax Year', type: 'number' },
      { key: 'interestRate', label: 'Interest Rate %', type: 'number' },
      { key: 'penaltyAmount', label: 'Penalty Amount', type: 'number' }
    ],
    aiFields: ['lienType', 'amount', 'debtorName', 'jurisdiction']
  },
  {
    id: 'environmentalrecords',
    name: 'Environmental Records',
    icon: '🌿',
    color: '#22c55e',
    description: 'Environmental assessments, contamination, and remediation',
    aiType: 'environmental',
    columns: ['siteName', 'recordType', 'status', 'riskLevel', 'agency'],
    fields: [
      { key: 'siteName', label: 'Site Name', type: 'text', required: true },
      { key: 'address', label: 'Address', type: 'text', required: true },
      { key: 'recordType', label: 'Record Type', type: 'select', options: ['contamination', 'permit', 'violation', 'assessment', 'remediation'], required: true },
      { key: 'agency', label: 'Agency', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'closed', 'monitoring', 'remediation', 'compliant'] },
      { key: 'riskLevel', label: 'Risk Level', type: 'select', options: ['low', 'medium', 'high', 'critical'] },
      { key: 'cleanupCost', label: 'Cleanup Cost', type: 'number' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'responsibleParty', label: 'Responsible Party', type: 'text' }
    ],
    aiFields: ['siteName', 'recordType', 'contaminants', 'riskLevel']
  },
  {
    id: 'campaignfinance',
    name: 'Campaign Finance',
    icon: '🗳️',
    color: '#0ea5e9',
    description: 'Political campaign contributions and expenditures',
    aiType: 'campaign',
    columns: ['committeeName', 'candidateName', 'filingType', 'amount', 'status'],
    fields: [
      { key: 'committeeName', label: 'Committee Name', type: 'text', required: true },
      { key: 'candidateName', label: 'Candidate Name', type: 'text' },
      { key: 'office', label: 'Office', type: 'text' },
      { key: 'party', label: 'Party', type: 'text' },
      { key: 'filingType', label: 'Filing Type', type: 'select', options: ['contribution', 'expenditure', 'quarterly', 'annual', 'amendment'], required: true },
      { key: 'amount', label: 'Amount', type: 'number', required: true },
      { key: 'donorName', label: 'Donor Name', type: 'text' },
      { key: 'donorAddress', label: 'Donor Address', type: 'text' },
      { key: 'electionCycle', label: 'Election Cycle', type: 'text' },
      { key: 'reportingPeriod', label: 'Reporting Period', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['filed', 'amended', 'under_review', 'approved', 'flagged'] }
    ],
    aiFields: ['committeeName', 'candidateName', 'amount', 'filingType']
  },
  {
    id: 'professionallicenses',
    name: 'Professional Licenses',
    icon: '🎓',
    color: '#14b8a6',
    description: 'Professional license verification and status tracking',
    aiType: 'license',
    columns: ['licenseNumber', 'holderName', 'profession', 'state', 'status'],
    fields: [
      { key: 'licenseNumber', label: 'License Number', type: 'text', required: true },
      { key: 'licenseType', label: 'License Type', type: 'text', required: true },
      { key: 'holderName', label: 'Holder Name', type: 'text', required: true },
      { key: 'profession', label: 'Profession', type: 'text', required: true },
      { key: 'issuingAuthority', label: 'Issuing Authority', type: 'text' },
      { key: 'state', label: 'State', type: 'text' },
      { key: 'issueDate', label: 'Issue Date', type: 'date' },
      { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'expired', 'suspended', 'revoked', 'pending_renewal'] },
      { key: 'address', label: 'Address', type: 'text' }
    ],
    aiFields: ['licenseType', 'holderName', 'profession', 'state']
  },
  {
    id: 'governmentcontracts',
    name: 'Government Contracts',
    icon: '📝',
    color: '#7c3aed',
    description: 'Federal and state government contract awards and tracking',
    aiType: 'contract',
    columns: ['contractNumber', 'title', 'agency', 'vendorName', 'contractValue'],
    fields: [
      { key: 'contractNumber', label: 'Contract Number', type: 'text', required: true },
      { key: 'title', label: 'Title', type: 'text', required: true },
      { key: 'agency', label: 'Agency', type: 'text', required: true },
      { key: 'vendorName', label: 'Vendor Name', type: 'text', required: true },
      { key: 'contractValue', label: 'Contract Value', type: 'number' },
      { key: 'startDate', label: 'Start Date', type: 'date' },
      { key: 'endDate', label: 'End Date', type: 'date' },
      { key: 'status', label: 'Status', type: 'select', options: ['active', 'completed', 'terminated', 'pending', 'awarded'] },
      { key: 'contractType', label: 'Contract Type', type: 'select', options: ['fixed_price', 'cost_plus', 'time_materials', 'indefinite_delivery', 'blanket'] },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'naicsCode', label: 'NAICS Code', type: 'text' },
      { key: 'placeOfPerformance', label: 'Place of Performance', type: 'text' }
    ],
    aiFields: ['title', 'agency', 'vendorName', 'contractValue', 'contractType']
  }
];

export const getFeature = (id) => features.find(f => f.id === id);
