const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../../.env') });
const { sequelize, User, FoiaRequest, TitleSearch, RegulatoryFiling, CourtRecord, PropertyRecord, BusinessFiling, BuildingPermit, VitalRecord, TaxLien, EnvironmentalRecord, CampaignFinance, ProfessionalLicense, GovernmentContract } = require('../models');

async function seed() {
  try {
    await sequelize.authenticate();
    console.log('Connected to database');
    await sequelize.sync({ force: true });
    console.log('Tables created');

    // Users
    await User.bulkCreate([
      { email: 'admin@publicrecords.gov', password: 'admin123', name: 'Sarah Mitchell', role: 'admin' },
      { email: 'analyst@publicrecords.gov', password: 'analyst123', name: 'James Chen', role: 'analyst' },
      { email: 'user@publicrecords.gov', password: 'user123', name: 'Maria Rodriguez', role: 'user' }
    ], { individualHooks: true });
    console.log('Users seeded');

    // FOIA Requests (15)
    await FoiaRequest.bulkCreate([
      { title: 'EPA Water Quality Reports 2024', agency: 'Environmental Protection Agency', status: 'in_progress', description: 'Request for all water quality testing reports in the Great Lakes region for fiscal year 2024', requestorName: 'John Anderson', requestorEmail: 'j.anderson@news.com', trackingNumber: 'FOIA-2024-00142', estimatedCost: 125.00, category: 'Environmental', priority: 'high' },
      { title: 'FBI Surveillance Records - Project Meridian', agency: 'Federal Bureau of Investigation', status: 'pending', description: 'Declassified surveillance documentation related to historical counterintelligence operations', requestorName: 'Lisa Park', requestorEmail: 'lpark@research.edu', trackingNumber: 'FOIA-2024-00287', estimatedCost: 450.00, category: 'Law Enforcement', priority: 'medium' },
      { title: 'DOD Military Base Environmental Impact', agency: 'Department of Defense', status: 'completed', description: 'Environmental impact assessments for decommissioned military installations', requestorName: 'Robert Williams', requestorEmail: 'rwilliams@envgroup.org', trackingNumber: 'FOIA-2024-00056', estimatedCost: 200.00, category: 'Military', priority: 'low' },
      { title: 'FDA Drug Approval Communications', agency: 'Food and Drug Administration', status: 'in_progress', description: 'Internal communications regarding fast-track drug approval process for pandemic therapeutics', requestorName: 'Emily Chen', requestorEmail: 'echen@pharmawatch.org', trackingNumber: 'FOIA-2024-00391', estimatedCost: 750.00, category: 'Healthcare', priority: 'urgent' },
      { title: 'ICE Detention Facility Inspections', agency: 'Immigration and Customs Enforcement', status: 'denied', description: 'Inspection reports for all ICE detention facilities in the Southwest region', requestorName: 'Carlos Mendez', requestorEmail: 'cmendez@aclu.org', trackingNumber: 'FOIA-2024-00198', estimatedCost: 300.00, category: 'Immigration', priority: 'high' },
      { title: 'FAA Drone Incident Reports', agency: 'Federal Aviation Administration', status: 'completed', description: 'All reported near-miss incidents between commercial aircraft and unmanned aerial vehicles', requestorName: 'Thomas Wright', requestorEmail: 'twright@aviation.com', trackingNumber: 'FOIA-2024-00423', estimatedCost: 175.00, category: 'Aviation', priority: 'medium' },
      { title: 'USDA Farm Subsidy Distribution', agency: 'Department of Agriculture', status: 'pending', description: 'Detailed breakdown of agricultural subsidies by state and crop type for 2023-2024', requestorName: 'Sarah Johnson', requestorEmail: 'sjohnson@farmreport.com', trackingNumber: 'FOIA-2024-00511', estimatedCost: 100.00, category: 'Agriculture', priority: 'low' },
      { title: 'SEC Insider Trading Investigations', agency: 'Securities and Exchange Commission', status: 'appealed', description: 'Records of insider trading investigations involving publicly traded tech companies', requestorName: 'David Kim', requestorEmail: 'dkim@finreporter.com', trackingNumber: 'FOIA-2024-00334', estimatedCost: 1200.00, category: 'Financial', priority: 'high' },
      { title: 'CDC Pandemic Response Emails', agency: 'Centers for Disease Control', status: 'in_progress', description: 'Email communications between CDC leadership regarding pandemic response protocols', requestorName: 'Amanda Foster', requestorEmail: 'afoster@healthnews.com', trackingNumber: 'FOIA-2024-00267', estimatedCost: 500.00, category: 'Healthcare', priority: 'urgent' },
      { title: 'DOE Nuclear Facility Safety Reports', agency: 'Department of Energy', status: 'completed', description: 'Safety inspection reports for all active nuclear power facilities', requestorName: 'Michael Brown', requestorEmail: 'mbrown@energywatch.org', trackingNumber: 'FOIA-2024-00089', estimatedCost: 350.00, category: 'Energy', priority: 'high' },
      { title: 'VA Hospital Wait Time Data', agency: 'Department of Veterans Affairs', status: 'pending', description: 'Patient wait time statistics for all VA medical centers nationwide', requestorName: 'Patricia Davis', requestorEmail: 'pdavis@vetadvocacy.org', trackingNumber: 'FOIA-2024-00445', estimatedCost: 75.00, category: 'Healthcare', priority: 'medium' },
      { title: 'FCC Broadband Mapping Accuracy', agency: 'Federal Communications Commission', status: 'in_progress', description: 'Data accuracy reports for the FCC broadband availability map', requestorName: 'Kevin O\'Brien', requestorEmail: 'kobrien@techpolicy.org', trackingNumber: 'FOIA-2024-00378', estimatedCost: 150.00, category: 'Technology', priority: 'medium' },
      { title: 'HUD Fair Housing Complaints', agency: 'Department of Housing and Urban Development', status: 'completed', description: 'Fair housing discrimination complaints filed in major metropolitan areas', requestorName: 'Rachel Green', requestorEmail: 'rgreen@housingwatch.org', trackingNumber: 'FOIA-2024-00156', estimatedCost: 225.00, category: 'Housing', priority: 'high' },
      { title: 'TSA Security Breach Reports', agency: 'Transportation Security Administration', status: 'denied', description: 'Reports of security breaches at major international airports', requestorName: 'James Miller', requestorEmail: 'jmiller@travelsafety.com', trackingNumber: 'FOIA-2024-00502', estimatedCost: 400.00, category: 'Security', priority: 'urgent' },
      { title: 'IRS Audit Selection Criteria', agency: 'Internal Revenue Service', status: 'pending', description: 'Documentation of criteria and algorithms used for selecting tax returns for audit', requestorName: 'Nancy Wilson', requestorEmail: 'nwilson@taxreform.org', trackingNumber: 'FOIA-2024-00467', estimatedCost: 600.00, category: 'Tax', priority: 'high' }
    ]);
    console.log('FOIA Requests seeded');

    // Title Searches (15)
    await TitleSearch.bulkCreate([
      { propertyAddress: '1420 Oak Valley Drive', county: 'Maricopa', state: 'AZ', ownerName: 'Henderson Family Trust', parcelNumber: 'APN-2024-44521', titleStatus: 'clear', assessedValue: 485000, marketValue: 625000, propertyType: 'Single Family', yearBuilt: 2015 },
      { propertyAddress: '8901 Sunset Blvd', county: 'Los Angeles', state: 'CA', ownerName: 'Westside Properties LLC', parcelNumber: 'APN-2024-78432', titleStatus: 'encumbered', assessedValue: 2150000, marketValue: 3200000, propertyType: 'Commercial', yearBuilt: 1988, liens: [{ type: 'mortgage', amount: 1800000 }] },
      { propertyAddress: '234 Peachtree Street NE', county: 'Fulton', state: 'GA', ownerName: 'Atlanta Tower Corp', parcelNumber: 'APN-2024-11234', titleStatus: 'clear', assessedValue: 12500000, marketValue: 18750000, propertyType: 'Office Building', yearBuilt: 2001 },
      { propertyAddress: '567 Lake Shore Drive', county: 'Cook', state: 'IL', ownerName: 'Margaret O\'Sullivan', parcelNumber: 'APN-2024-55678', titleStatus: 'pending', assessedValue: 890000, marketValue: 1150000, propertyType: 'Condominium', yearBuilt: 2010 },
      { propertyAddress: '789 Ranch Road', county: 'Travis', state: 'TX', ownerName: 'Lone Star Holdings', parcelNumber: 'APN-2024-33789', titleStatus: 'disputed', assessedValue: 1200000, marketValue: 1575000, propertyType: 'Ranch', yearBuilt: 1975, encumbrances: [{ type: 'easement', description: 'Utility easement' }] },
      { propertyAddress: '1100 Broadway', county: 'New York', state: 'NY', ownerName: 'Broadway Investment Group', parcelNumber: 'APN-2024-99100', titleStatus: 'encumbered', assessedValue: 8900000, marketValue: 14200000, propertyType: 'Mixed Use', yearBuilt: 1925 },
      { propertyAddress: '45 Harbor View Lane', county: 'Miami-Dade', state: 'FL', ownerName: 'Carlos & Elena Vasquez', parcelNumber: 'APN-2024-22045', titleStatus: 'clear', assessedValue: 1850000, marketValue: 2400000, propertyType: 'Waterfront', yearBuilt: 2019 },
      { propertyAddress: '3200 Mountain View Road', county: 'Denver', state: 'CO', ownerName: 'Rocky Mountain Estates', parcelNumber: 'APN-2024-66320', titleStatus: 'clear', assessedValue: 720000, marketValue: 945000, propertyType: 'Single Family', yearBuilt: 2008 },
      { propertyAddress: '901 Industrial Parkway', county: 'Wayne', state: 'MI', ownerName: 'Motor City Manufacturing', parcelNumber: 'APN-2024-88901', titleStatus: 'encumbered', assessedValue: 3400000, marketValue: 4100000, propertyType: 'Industrial', yearBuilt: 1965 },
      { propertyAddress: '156 Colonial Drive', county: 'Fairfax', state: 'VA', ownerName: 'James & Patricia Whitmore', parcelNumber: 'APN-2024-44156', titleStatus: 'clear', assessedValue: 950000, marketValue: 1200000, propertyType: 'Single Family', yearBuilt: 1998 },
      { propertyAddress: '2800 Pacific Coast Hwy', county: 'Orange', state: 'CA', ownerName: 'Pacific Shores LLC', parcelNumber: 'APN-2024-77280', titleStatus: 'pending', assessedValue: 4500000, marketValue: 6800000, propertyType: 'Resort', yearBuilt: 2005 },
      { propertyAddress: '400 State Street', county: 'Dane', state: 'WI', ownerName: 'Badger Realty Trust', parcelNumber: 'APN-2024-33400', titleStatus: 'clear', assessedValue: 580000, marketValue: 725000, propertyType: 'Retail', yearBuilt: 1990 },
      { propertyAddress: '1750 Research Blvd', county: 'Wake', state: 'NC', ownerName: 'Triangle Tech Park', parcelNumber: 'APN-2024-55175', titleStatus: 'clear', assessedValue: 6200000, marketValue: 8500000, propertyType: 'Office Park', yearBuilt: 2012 },
      { propertyAddress: '88 Vineyard Way', county: 'Napa', state: 'CA', ownerName: 'Napa Valley Estates', parcelNumber: 'APN-2024-11088', titleStatus: 'encumbered', assessedValue: 7800000, marketValue: 12000000, propertyType: 'Agricultural', yearBuilt: 1960 },
      { propertyAddress: '620 Magnolia Street', county: 'Orleans', state: 'LA', ownerName: 'Crescent City Properties', parcelNumber: 'APN-2024-22620', titleStatus: 'disputed', assessedValue: 445000, marketValue: 590000, propertyType: 'Historic', yearBuilt: 1890 }
    ]);
    console.log('Title Searches seeded');

    // Regulatory Filings (15)
    await RegulatoryFiling.bulkCreate([
      { filingType: 'Annual Report', entityName: 'TechVision Corp', regulatoryBody: 'SEC', filingNumber: 'SEC-2024-AR-001', status: 'approved', description: 'Annual financial report for fiscal year 2023', industry: 'Technology', complianceScore: 95 },
      { filingType: 'Environmental Impact', entityName: 'GreenEnergy Solutions', regulatoryBody: 'EPA', filingNumber: 'EPA-2024-EIS-042', status: 'under_review', description: 'Environmental impact statement for new solar farm installation', industry: 'Energy', complianceScore: 88 },
      { filingType: 'Drug Application', entityName: 'BioPharm Labs', regulatoryBody: 'FDA', filingNumber: 'FDA-2024-NDA-118', status: 'submitted', description: 'New drug application for cardiovascular therapeutic', industry: 'Pharmaceutical', complianceScore: 92 },
      { filingType: 'Banking Compliance', entityName: 'National Trust Bank', regulatoryBody: 'FDIC', filingNumber: 'FDIC-2024-BC-067', status: 'approved', description: 'Quarterly compliance report and stress test results', industry: 'Banking', complianceScore: 97 },
      { filingType: 'Telecom License', entityName: 'WaveConnect Inc', regulatoryBody: 'FCC', filingNumber: 'FCC-2024-TL-234', status: 'under_review', description: '5G spectrum license application for metropolitan area', industry: 'Telecommunications', complianceScore: 85 },
      { filingType: 'Safety Report', entityName: 'AutoDrive Systems', regulatoryBody: 'NHTSA', filingNumber: 'NHTSA-2024-SR-089', status: 'amended', description: 'Autonomous vehicle safety certification report', industry: 'Automotive', complianceScore: 78 },
      { filingType: 'Insurance Filing', entityName: 'SafeGuard Insurance', regulatoryBody: 'State Insurance Commission', filingNumber: 'SIC-2024-IF-156', status: 'approved', description: 'Rate increase filing for commercial property insurance', industry: 'Insurance', complianceScore: 91 },
      { filingType: 'Air Quality Permit', entityName: 'SteelWorks Manufacturing', regulatoryBody: 'EPA', filingNumber: 'EPA-2024-AQ-073', status: 'rejected', description: 'Air quality permit renewal for steel manufacturing facility', industry: 'Manufacturing', complianceScore: 62, penaltyAmount: 150000 },
      { filingType: 'Securities Registration', entityName: 'CloudScale Technologies', regulatoryBody: 'SEC', filingNumber: 'SEC-2024-S1-445', status: 'submitted', description: 'S-1 registration statement for initial public offering', industry: 'Technology', complianceScore: 90 },
      { filingType: 'Nuclear License', entityName: 'Pacific Power Nuclear', regulatoryBody: 'NRC', filingNumber: 'NRC-2024-NL-012', status: 'under_review', description: 'Operating license renewal for nuclear power plant', industry: 'Energy', complianceScore: 96 },
      { filingType: 'Food Safety', entityName: 'FreshHarvest Foods', regulatoryBody: 'FDA', filingNumber: 'FDA-2024-FS-289', status: 'approved', description: 'Food safety modernization act compliance filing', industry: 'Food & Beverage', complianceScore: 94 },
      { filingType: 'Mining Permit', entityName: 'Mountain Resources Corp', regulatoryBody: 'Bureau of Land Management', filingNumber: 'BLM-2024-MP-034', status: 'submitted', description: 'Mining permit application for copper extraction', industry: 'Mining', complianceScore: 80 },
      { filingType: 'Aviation Certificate', entityName: 'SkyLine Airlines', regulatoryBody: 'FAA', filingNumber: 'FAA-2024-AC-567', status: 'approved', description: 'Air carrier certificate renewal and fleet update', industry: 'Aviation', complianceScore: 98 },
      { filingType: 'Chemical Registration', entityName: 'ChemTech Industries', regulatoryBody: 'EPA', filingNumber: 'EPA-2024-CR-198', status: 'under_review', description: 'New chemical substance registration under TSCA', industry: 'Chemical', complianceScore: 83 },
      { filingType: 'Financial Audit', entityName: 'Meridian Capital Group', regulatoryBody: 'SEC', filingNumber: 'SEC-2024-FA-321', status: 'submitted', description: 'Independent audit report for registered investment advisor', industry: 'Financial Services', complianceScore: 89 }
    ]);
    console.log('Regulatory Filings seeded');

    // Court Records (15)
    await CourtRecord.bulkCreate([
      { caseNumber: 'CV-2024-001234', caseTitle: 'Smith v. Metro Healthcare Systems', court: 'U.S. District Court, Southern District', judge: 'Hon. Patricia Williams', plaintiff: 'Robert Smith', defendant: 'Metro Healthcare Systems', caseType: 'civil', status: 'open', description: 'Medical malpractice claim alleging negligent surgical procedure', jurisdiction: 'Federal', damagesAmount: 2500000 },
      { caseNumber: 'CR-2024-005678', caseTitle: 'United States v. DataCorp International', court: 'U.S. District Court, Northern District', judge: 'Hon. Michael Chen', plaintiff: 'United States', defendant: 'DataCorp International', caseType: 'criminal', status: 'open', description: 'Federal wire fraud and data breach charges', jurisdiction: 'Federal', damagesAmount: 15000000 },
      { caseNumber: 'BK-2024-009012', caseTitle: 'In Re: Evergreen Retail Group', court: 'U.S. Bankruptcy Court', judge: 'Hon. Sandra Martinez', plaintiff: 'Evergreen Retail Group', defendant: 'Various Creditors', caseType: 'bankruptcy', status: 'open', description: 'Chapter 11 reorganization filing for national retail chain', jurisdiction: 'Federal', damagesAmount: 450000000 },
      { caseNumber: 'CV-2024-002345', caseTitle: 'Johnson v. City of Riverside', court: 'Superior Court of California', judge: 'Hon. David Park', plaintiff: 'Maria Johnson', defendant: 'City of Riverside', caseType: 'civil', status: 'settled', description: 'Civil rights violation claim against municipal police department', jurisdiction: 'State', damagesAmount: 750000 },
      { caseNumber: 'FM-2024-003456', caseTitle: 'Anderson v. Anderson', court: 'Family Court, Cook County', judge: 'Hon. Lisa Thompson', plaintiff: 'Jennifer Anderson', defendant: 'Mark Anderson', caseType: 'family', status: 'open', description: 'Contested divorce proceedings with custody dispute', jurisdiction: 'State', damagesAmount: 5000000 },
      { caseNumber: 'AP-2024-004567', caseTitle: 'TechStart Inc v. Federal Trade Commission', court: 'U.S. Court of Appeals, 9th Circuit', judge: 'Panel of Three', plaintiff: 'TechStart Inc', defendant: 'FTC', caseType: 'appellate', status: 'appealed', description: 'Appeal of antitrust enforcement action against tech startup', jurisdiction: 'Federal', damagesAmount: 85000000 },
      { caseNumber: 'CV-2024-006789', caseTitle: 'Environmental Defense Fund v. PetroChem Corp', court: 'U.S. District Court, Eastern District', judge: 'Hon. Robert Johnson', plaintiff: 'Environmental Defense Fund', defendant: 'PetroChem Corp', caseType: 'civil', status: 'open', description: 'Environmental contamination class action lawsuit', jurisdiction: 'Federal', damagesAmount: 200000000 },
      { caseNumber: 'CR-2024-007890', caseTitle: 'State v. Marcus Webb', court: 'Circuit Court, Fulton County', judge: 'Hon. Angela Davis', plaintiff: 'State of Georgia', defendant: 'Marcus Webb', caseType: 'criminal', status: 'closed', description: 'Securities fraud and money laundering charges', jurisdiction: 'State', damagesAmount: 12000000 },
      { caseNumber: 'CV-2024-008901', caseTitle: 'Patent Holdings LLC v. InnovateTech', court: 'U.S. District Court, District of Delaware', judge: 'Hon. Thomas Baker', plaintiff: 'Patent Holdings LLC', defendant: 'InnovateTech Inc', caseType: 'civil', status: 'open', description: 'Patent infringement claim for semiconductor technology', jurisdiction: 'Federal', damagesAmount: 350000000 },
      { caseNumber: 'CV-2024-010123', caseTitle: 'Workers United v. Mega Logistics', court: 'National Labor Relations Board', judge: 'Hon. Karen White', plaintiff: 'Workers United Local 127', defendant: 'Mega Logistics Inc', caseType: 'civil', status: 'open', description: 'Unfair labor practice complaint regarding union organizing', jurisdiction: 'Federal', damagesAmount: 5000000 },
      { caseNumber: 'BK-2024-011234', caseTitle: 'In Re: Coastal Airlines', court: 'U.S. Bankruptcy Court, Southern District', judge: 'Hon. Richard Lee', plaintiff: 'Coastal Airlines', defendant: 'Various Creditors', caseType: 'bankruptcy', status: 'open', description: 'Chapter 7 liquidation of regional airline', jurisdiction: 'Federal', damagesAmount: 180000000 },
      { caseNumber: 'CV-2024-012345', caseTitle: 'Consumer Advocacy Group v. BigPharma Inc', court: 'Superior Court, Los Angeles', judge: 'Hon. Maria Santos', plaintiff: 'Consumer Advocacy Group', defendant: 'BigPharma Inc', caseType: 'civil', status: 'dismissed', description: 'Consumer protection class action for misleading drug marketing', jurisdiction: 'State', damagesAmount: 500000000 },
      { caseNumber: 'CR-2024-013456', caseTitle: 'United States v. Global Trade Networks', court: 'U.S. District Court, SDNY', judge: 'Hon. James O\'Connor', plaintiff: 'United States', defendant: 'Global Trade Networks', caseType: 'criminal', status: 'open', description: 'RICO charges related to international trade fraud', jurisdiction: 'Federal', damagesAmount: 75000000 },
      { caseNumber: 'FM-2024-014567', caseTitle: 'Hernandez v. Hernandez', court: 'Family Court, Harris County', judge: 'Hon. Carmen Reyes', plaintiff: 'Ana Hernandez', defendant: 'Luis Hernandez', caseType: 'family', status: 'settled', description: 'Child custody modification and support adjustment', jurisdiction: 'State', damagesAmount: 250000 },
      { caseNumber: 'AP-2024-015678', caseTitle: 'National Association of Builders v. EPA', court: 'U.S. Court of Appeals, DC Circuit', judge: 'Panel of Three', plaintiff: 'National Association of Builders', defendant: 'EPA', caseType: 'appellate', status: 'open', description: 'Challenge to new environmental regulations on construction', jurisdiction: 'Federal', damagesAmount: 0 }
    ]);
    console.log('Court Records seeded');

    // Property Records (15)
    await PropertyRecord.bulkCreate([
      { address: '245 Elm Street', city: 'Portland', state: 'OR', zipCode: '97201', ownerName: 'David & Sarah Mitchell', propertyType: 'residential', assessedValue: 485000, marketValue: 625000, taxAmount: 7250, squareFeet: 2400, lotSize: 0.25, yearBuilt: 2005, bedrooms: 4, bathrooms: 2.5, lastSalePrice: 550000, zoningCode: 'R-1' },
      { address: '8800 Commerce Drive', city: 'Dallas', state: 'TX', zipCode: '75201', ownerName: 'DFW Business Park LLC', propertyType: 'commercial', assessedValue: 4200000, marketValue: 5800000, taxAmount: 98500, squareFeet: 45000, lotSize: 3.5, yearBuilt: 2010, zoningCode: 'C-2' },
      { address: '1234 Maple Avenue', city: 'Chicago', state: 'IL', zipCode: '60601', ownerName: 'Chicago Residential Trust', propertyType: 'residential', assessedValue: 320000, marketValue: 425000, taxAmount: 5800, squareFeet: 1800, lotSize: 0.15, yearBuilt: 1925, bedrooms: 3, bathrooms: 2, lastSalePrice: 380000, zoningCode: 'R-2' },
      { address: '5500 Industrial Blvd', city: 'Houston', state: 'TX', zipCode: '77001', ownerName: 'Gulf Coast Industries', propertyType: 'industrial', assessedValue: 8900000, marketValue: 11200000, taxAmount: 156000, squareFeet: 125000, lotSize: 12.0, yearBuilt: 1998, zoningCode: 'I-1' },
      { address: '320 Ocean Avenue', city: 'Miami', state: 'FL', zipCode: '33101', ownerName: 'Tropical Living Partners', propertyType: 'residential', assessedValue: 1250000, marketValue: 1800000, taxAmount: 18500, squareFeet: 3200, lotSize: 0.35, yearBuilt: 2018, bedrooms: 5, bathrooms: 4, lastSalePrice: 1650000, zoningCode: 'R-1' },
      { address: '900 Farmland Road', city: 'Des Moines', state: 'IA', zipCode: '50301', ownerName: 'Heartland Agricultural Co', propertyType: 'agricultural', assessedValue: 2100000, marketValue: 2800000, taxAmount: 24500, squareFeet: 5000, lotSize: 320.0, yearBuilt: 1955, zoningCode: 'A-1' },
      { address: '1600 Tech Parkway', city: 'San Jose', state: 'CA', zipCode: '95101', ownerName: 'Silicon Valley Office Trust', propertyType: 'commercial', assessedValue: 15000000, marketValue: 22000000, taxAmount: 245000, squareFeet: 85000, lotSize: 5.0, yearBuilt: 2015, zoningCode: 'C-3' },
      { address: '412 Heritage Lane', city: 'Charleston', state: 'SC', zipCode: '29401', ownerName: 'Lowcountry Preservation Society', propertyType: 'residential', assessedValue: 890000, marketValue: 1150000, taxAmount: 8900, squareFeet: 3800, lotSize: 0.45, yearBuilt: 1840, bedrooms: 6, bathrooms: 3.5, lastSalePrice: 1050000, zoningCode: 'HR-1' },
      { address: '7700 Airport Road', city: 'Phoenix', state: 'AZ', zipCode: '85001', ownerName: 'Sky Harbor Partners LLC', propertyType: 'commercial', assessedValue: 6500000, marketValue: 8900000, taxAmount: 112000, squareFeet: 55000, lotSize: 8.0, yearBuilt: 2002, zoningCode: 'C-4' },
      { address: '155 Mountain View Terrace', city: 'Denver', state: 'CO', zipCode: '80201', ownerName: 'Jennifer & Tom Blackwell', propertyType: 'residential', assessedValue: 675000, marketValue: 850000, taxAmount: 6200, squareFeet: 2800, lotSize: 0.30, yearBuilt: 2012, bedrooms: 4, bathrooms: 3, lastSalePrice: 780000, zoningCode: 'R-1' },
      { address: '3000 Warehouse District', city: 'Nashville', state: 'TN', zipCode: '37201', ownerName: 'Music City Investments', propertyType: 'commercial', assessedValue: 3800000, marketValue: 5200000, taxAmount: 67000, squareFeet: 35000, lotSize: 2.5, yearBuilt: 1920, zoningCode: 'MU-1' },
      { address: 'Lot 45 Desert Winds', city: 'Scottsdale', state: 'AZ', zipCode: '85251', ownerName: 'Arizona Land Holdings', propertyType: 'vacant', assessedValue: 450000, marketValue: 680000, taxAmount: 5400, lotSize: 2.0, zoningCode: 'R-1' },
      { address: '2100 University Place', city: 'Boston', state: 'MA', zipCode: '02101', ownerName: 'Commonwealth Realty Trust', propertyType: 'commercial', assessedValue: 9800000, marketValue: 14500000, taxAmount: 178000, squareFeet: 72000, lotSize: 1.5, yearBuilt: 1965, zoningCode: 'C-2' },
      { address: '888 Vineyard Estate', city: 'Napa', state: 'CA', zipCode: '94558', ownerName: 'Wine Country Estates LLC', propertyType: 'agricultural', assessedValue: 5600000, marketValue: 8200000, taxAmount: 62000, squareFeet: 8500, lotSize: 45.0, yearBuilt: 1975, zoningCode: 'AG-1' },
      { address: '500 Riverfront Plaza', city: 'Minneapolis', state: 'MN', zipCode: '55401', ownerName: 'North Star Development', propertyType: 'commercial', assessedValue: 7200000, marketValue: 9800000, taxAmount: 134000, squareFeet: 62000, lotSize: 2.0, yearBuilt: 2008, zoningCode: 'CBD' }
    ]);
    console.log('Property Records seeded');

    // Business Filings (15)
    await BusinessFiling.bulkCreate([
      { businessName: 'TechNova Solutions Inc', entityType: 'Corporation', stateOfIncorporation: 'Delaware', filingNumber: 'BF-2024-001', registeredAgent: 'CT Corporation', principalAddress: '100 Innovation Drive, San Francisco, CA', status: 'active', industry: 'Software', officers: [{ name: 'John Lee', title: 'CEO' }, { name: 'Sarah Kim', title: 'CFO' }] },
      { businessName: 'Green Valley Farms LLC', entityType: 'LLC', stateOfIncorporation: 'Iowa', filingNumber: 'BF-2024-002', registeredAgent: 'Robert Green', principalAddress: '500 Farm Road, Des Moines, IA', status: 'active', industry: 'Agriculture', officers: [{ name: 'Robert Green', title: 'Managing Member' }] },
      { businessName: 'Pacific Coast Builders', entityType: 'Corporation', stateOfIncorporation: 'California', filingNumber: 'BF-2024-003', registeredAgent: 'LegalZoom', principalAddress: '800 Construction Way, Los Angeles, CA', status: 'active', industry: 'Construction' },
      { businessName: 'Meridian Healthcare Partners', entityType: 'Partnership', stateOfIncorporation: 'New York', filingNumber: 'BF-2024-004', registeredAgent: 'National Registered Agents', principalAddress: '200 Medical Plaza, New York, NY', status: 'active', industry: 'Healthcare' },
      { businessName: 'Sunset Restaurant Group LLC', entityType: 'LLC', stateOfIncorporation: 'Florida', filingNumber: 'BF-2024-005', registeredAgent: 'Florida Agents Inc', principalAddress: '450 Dining Blvd, Miami, FL', status: 'active', industry: 'Food & Beverage' },
      { businessName: 'DataStream Analytics Corp', entityType: 'Corporation', stateOfIncorporation: 'Delaware', filingNumber: 'BF-2024-006', registeredAgent: 'CT Corporation', principalAddress: '300 Data Drive, Austin, TX', status: 'active', industry: 'Data Analytics' },
      { businessName: 'Heritage Antiques', entityType: 'Sole Proprietorship', stateOfIncorporation: 'Virginia', filingNumber: 'BF-2024-007', registeredAgent: 'Margaret Thompson', principalAddress: '75 Main Street, Richmond, VA', status: 'active', industry: 'Retail' },
      { businessName: 'Summit Financial Advisors LLC', entityType: 'LLC', stateOfIncorporation: 'Colorado', filingNumber: 'BF-2024-008', registeredAgent: 'Colorado Registered Agents', principalAddress: '1200 Finance Way, Denver, CO', status: 'active', industry: 'Financial Services' },
      { businessName: 'AutoParts Unlimited Inc', entityType: 'Corporation', stateOfIncorporation: 'Michigan', filingNumber: 'BF-2024-009', registeredAgent: 'Michigan Corp Services', principalAddress: '4500 Motor Blvd, Detroit, MI', status: 'dissolved', industry: 'Automotive' },
      { businessName: 'Clean Energy Ventures', entityType: 'Corporation', stateOfIncorporation: 'Texas', filingNumber: 'BF-2024-010', registeredAgent: 'Texas Registered Agents', principalAddress: '600 Solar Lane, Houston, TX', status: 'active', industry: 'Renewable Energy' },
      { businessName: 'Artisan Coffee Roasters LLC', entityType: 'LLC', stateOfIncorporation: 'Oregon', filingNumber: 'BF-2024-011', registeredAgent: 'Northwest Agents', principalAddress: '225 Roast Ave, Portland, OR', status: 'active', industry: 'Food & Beverage' },
      { businessName: 'Quantum Computing Labs', entityType: 'Corporation', stateOfIncorporation: 'Massachusetts', filingNumber: 'BF-2024-012', registeredAgent: 'CT Corporation', principalAddress: '900 Research Park, Cambridge, MA', status: 'active', industry: 'Technology' },
      { businessName: 'Coastal Property Management', entityType: 'LLC', stateOfIncorporation: 'South Carolina', filingNumber: 'BF-2024-013', registeredAgent: 'SC Business Services', principalAddress: '350 Beach Road, Charleston, SC', status: 'suspended', industry: 'Real Estate' },
      { businessName: 'Liberty Defense Foundation', entityType: 'Non-Profit', stateOfIncorporation: 'Washington DC', filingNumber: 'BF-2024-014', registeredAgent: 'DC Nonprofit Services', principalAddress: '1400 K Street NW, Washington, DC', status: 'active', industry: 'Legal Services' },
      { businessName: 'Mountain View Logistics', entityType: 'Corporation', stateOfIncorporation: 'Tennessee', filingNumber: 'BF-2024-015', registeredAgent: 'Tennessee Corp Services', principalAddress: '2800 Transport Way, Nashville, TN', status: 'active', industry: 'Logistics' }
    ]);
    console.log('Business Filings seeded');

    // Building Permits (15)
    await BuildingPermit.bulkCreate([
      { permitNumber: 'BP-2024-0001', propertyAddress: '1200 Oak Street, Portland, OR', permitType: 'new_construction', applicantName: 'Pacific Builders Inc', contractorName: 'Pacific Builders Inc', status: 'approved', estimatedCost: 450000, description: 'New single-family residence, 2800 sq ft', municipality: 'Portland' },
      { permitNumber: 'BP-2024-0002', propertyAddress: '500 Main Street, Austin, TX', permitType: 'renovation', applicantName: 'Downtown Properties LLC', contractorName: 'Texas Renovations', status: 'completed', estimatedCost: 125000, description: 'Commercial building facade renovation and ADA compliance upgrade', municipality: 'Austin' },
      { permitNumber: 'BP-2024-0003', propertyAddress: '8900 Industrial Park, Detroit, MI', permitType: 'demolition', applicantName: 'Motor City Redevelopment', contractorName: 'Demolition Experts Inc', status: 'approved', estimatedCost: 85000, description: 'Demolition of abandoned factory building', municipality: 'Detroit' },
      { permitNumber: 'BP-2024-0004', propertyAddress: '234 Residential Lane, Denver, CO', permitType: 'electrical', applicantName: 'John Smith', contractorName: 'Peak Electric Services', status: 'inspection_pending', estimatedCost: 15000, description: 'Full electrical panel upgrade and EV charger installation', municipality: 'Denver' },
      { permitNumber: 'BP-2024-0005', propertyAddress: '567 Beach Road, Miami, FL', permitType: 'new_construction', applicantName: 'Tropical Homes LLC', contractorName: 'Coastal Construction Corp', status: 'applied', estimatedCost: 1200000, description: 'New luxury waterfront residence with pool and dock', municipality: 'Miami' },
      { permitNumber: 'BP-2024-0006', propertyAddress: '901 Restaurant Row, Nashville, TN', permitType: 'renovation', applicantName: 'Music City Eats LLC', contractorName: 'Nashville Contractors', status: 'approved', estimatedCost: 250000, description: 'Restaurant build-out with commercial kitchen installation', municipality: 'Nashville' },
      { permitNumber: 'BP-2024-0007', propertyAddress: '345 Tech Campus, San Jose, CA', permitType: 'new_construction', applicantName: 'Silicon Valley Dev Corp', contractorName: 'Bay Area Builders', status: 'approved', estimatedCost: 25000000, description: 'New 5-story office building with underground parking', municipality: 'San Jose' },
      { permitNumber: 'BP-2024-0008', propertyAddress: '678 Suburban Drive, Phoenix, AZ', permitType: 'plumbing', applicantName: 'Maria Garcia', contractorName: 'Desert Plumbing Co', status: 'completed', estimatedCost: 8500, description: 'Whole-house repiping from polybutylene to copper', municipality: 'Phoenix' },
      { permitNumber: 'BP-2024-0009', propertyAddress: '1100 Historic District, Charleston, SC', permitType: 'renovation', applicantName: 'Preservation Partners', contractorName: 'Heritage Restoration Inc', status: 'approved', estimatedCost: 375000, description: 'Historic building restoration maintaining original architecture', municipality: 'Charleston' },
      { permitNumber: 'BP-2024-0010', propertyAddress: '2200 Shopping Center, Dallas, TX', permitType: 'mechanical', applicantName: 'Retail Properties Group', contractorName: 'Climate Control Systems', status: 'applied', estimatedCost: 180000, description: 'Complete HVAC system replacement for retail complex', municipality: 'Dallas' },
      { permitNumber: 'BP-2024-0011', propertyAddress: '440 Lakeside Ave, Chicago, IL', permitType: 'new_construction', applicantName: 'Lakefront Development', contractorName: 'Windy City Builders', status: 'denied', estimatedCost: 8500000, description: 'New 12-unit luxury condominium building', municipality: 'Chicago' },
      { permitNumber: 'BP-2024-0012', propertyAddress: '789 College Ave, Boston, MA', permitType: 'renovation', applicantName: 'University Housing Corp', contractorName: 'New England Contractors', status: 'approved', estimatedCost: 450000, description: 'Student housing renovation and fire safety upgrades', municipality: 'Boston' },
      { permitNumber: 'BP-2024-0013', propertyAddress: '1500 Solar Farm Road, Tucson, AZ', permitType: 'electrical', applicantName: 'Arizona Solar Energy', contractorName: 'Solar Installation Pros', status: 'completed', estimatedCost: 2500000, description: 'Commercial solar panel installation - 500kW system', municipality: 'Tucson' },
      { permitNumber: 'BP-2024-0014', propertyAddress: '600 Warehouse District, Seattle, WA', permitType: 'renovation', applicantName: 'PNW Properties LLC', contractorName: 'Seattle Urban Builders', status: 'inspection_pending', estimatedCost: 890000, description: 'Warehouse to mixed-use residential conversion', municipality: 'Seattle' },
      { permitNumber: 'BP-2024-0015', propertyAddress: '3300 Hospital Way, Atlanta, GA', permitType: 'new_construction', applicantName: 'Southeast Medical Center', contractorName: 'Healthcare Construction Inc', status: 'approved', estimatedCost: 45000000, description: 'New medical facility wing with surgical suites', municipality: 'Atlanta' }
    ]);
    console.log('Building Permits seeded');

    // Vital Records (15)
    await VitalRecord.bulkCreate([
      { recordType: 'birth', fullName: 'Emma Grace Thompson', dateOfEvent: '2024-03-15', county: 'Maricopa', state: 'AZ', certificateNumber: 'BR-2024-001234', location: 'Phoenix General Hospital', status: 'verified' },
      { recordType: 'marriage', fullName: 'James Wilson & Katherine Chen', dateOfEvent: '2024-06-22', county: 'Los Angeles', state: 'CA', certificateNumber: 'MR-2024-005678', location: 'Los Angeles County Clerk', status: 'verified' },
      { recordType: 'death', fullName: 'Harold Robert Stevens', dateOfEvent: '2024-01-08', county: 'Cook', state: 'IL', certificateNumber: 'DR-2024-000891', location: 'Northwestern Memorial Hospital', status: 'verified' },
      { recordType: 'divorce', fullName: 'Michael & Sandra Patterson', dateOfEvent: '2024-04-30', county: 'Harris', state: 'TX', certificateNumber: 'DV-2024-002345', location: 'Harris County Court', status: 'verified' },
      { recordType: 'birth', fullName: 'Lucas Alexander Rivera', dateOfEvent: '2024-07-12', county: 'Miami-Dade', state: 'FL', certificateNumber: 'BR-2024-006789', location: 'Baptist Health South Florida', status: 'verified' },
      { recordType: 'marriage', fullName: 'David Park & Emily Nguyen', dateOfEvent: '2024-09-14', county: 'King', state: 'WA', certificateNumber: 'MR-2024-003456', location: 'Seattle City Hall', status: 'verified' },
      { recordType: 'death', fullName: 'Virginia Mae Caldwell', dateOfEvent: '2024-02-28', county: 'Fulton', state: 'GA', certificateNumber: 'DR-2024-001567', location: 'Emory University Hospital', status: 'verified' },
      { recordType: 'birth', fullName: 'Sophia Marie Johnson', dateOfEvent: '2024-05-03', county: 'Travis', state: 'TX', certificateNumber: 'BR-2024-004890', location: 'Seton Medical Center', status: 'pending' },
      { recordType: 'marriage', fullName: 'Robert Martinez & Lisa Chang', dateOfEvent: '2024-11-01', county: 'Denver', state: 'CO', certificateNumber: 'MR-2024-007123', location: 'Denver County Clerk', status: 'verified' },
      { recordType: 'death', fullName: 'William James Crawford', dateOfEvent: '2024-08-19', county: 'Allegheny', state: 'PA', certificateNumber: 'DR-2024-005234', location: 'UPMC Presbyterian', status: 'verified' },
      { recordType: 'divorce', fullName: 'Thomas & Angela Richardson', dateOfEvent: '2024-03-22', county: 'Maricopa', state: 'AZ', certificateNumber: 'DV-2024-003567', location: 'Maricopa County Superior Court', status: 'verified' },
      { recordType: 'birth', fullName: 'Oliver Benjamin Wright', dateOfEvent: '2024-10-08', county: 'Suffolk', state: 'MA', certificateNumber: 'BR-2024-008901', location: 'Massachusetts General Hospital', status: 'verified' },
      { recordType: 'marriage', fullName: 'Christopher Lee & Amanda Foster', dateOfEvent: '2024-08-05', county: 'Mecklenburg', state: 'NC', certificateNumber: 'MR-2024-006234', location: 'Charlotte City Hall', status: 'amended' },
      { recordType: 'death', fullName: 'Dorothy Eleanor Simmons', dateOfEvent: '2024-06-14', county: 'Orleans', state: 'LA', certificateNumber: 'DR-2024-004567', location: 'Ochsner Medical Center', status: 'verified' },
      { recordType: 'birth', fullName: 'Isabella Rose Garcia', dateOfEvent: '2024-12-01', county: 'Bexar', state: 'TX', certificateNumber: 'BR-2024-009012', location: 'Methodist Hospital', status: 'pending' }
    ]);
    console.log('Vital Records seeded');

    // Tax Liens (15)
    await TaxLien.bulkCreate([
      { lienNumber: 'TL-2024-001', debtorName: 'Jackson Enterprises LLC', lienType: 'federal', amount: 245000, status: 'active', propertyAddress: '1200 Business Park, Atlanta, GA', jurisdiction: 'IRS', taxYear: 2022, interestRate: 7.5, penaltyAmount: 24500 },
      { lienNumber: 'TL-2024-002', debtorName: 'Sarah Mitchell', lienType: 'property', amount: 12500, status: 'active', propertyAddress: '456 Oak Lane, Portland, OR', jurisdiction: 'Multnomah County', taxYear: 2023, interestRate: 12.0, penaltyAmount: 1250 },
      { lienNumber: 'TL-2024-003', debtorName: 'Metro Construction Corp', lienType: 'state', amount: 89000, status: 'released', propertyAddress: '789 Industrial Ave, Houston, TX', jurisdiction: 'Texas Comptroller', taxYear: 2021, interestRate: 6.0, penaltyAmount: 8900 },
      { lienNumber: 'TL-2024-004', debtorName: 'David Chen', lienType: 'income', amount: 156000, status: 'active', jurisdiction: 'IRS', taxYear: 2022, interestRate: 7.5, penaltyAmount: 15600 },
      { lienNumber: 'TL-2024-005', debtorName: 'Sunrise Restaurant Group', lienType: 'payroll', amount: 67000, status: 'paid', propertyAddress: '300 Restaurant Row, Miami, FL', jurisdiction: 'IRS', taxYear: 2023, interestRate: 7.5, penaltyAmount: 6700 },
      { lienNumber: 'TL-2024-006', debtorName: 'Continental Properties LLC', lienType: 'property', amount: 340000, status: 'active', propertyAddress: '5500 Commercial Blvd, Chicago, IL', jurisdiction: 'Cook County', taxYear: 2022, interestRate: 18.0, penaltyAmount: 34000 },
      { lienNumber: 'TL-2024-007', debtorName: 'Patricia Williams', lienType: 'federal', amount: 78000, status: 'subordinated', propertyAddress: '200 Riverside Dr, New York, NY', jurisdiction: 'IRS', taxYear: 2021, interestRate: 7.5, penaltyAmount: 7800 },
      { lienNumber: 'TL-2024-008', debtorName: 'Blue Sky Aviation', lienType: 'state', amount: 125000, status: 'active', propertyAddress: '900 Airport Rd, Phoenix, AZ', jurisdiction: 'Arizona DOR', taxYear: 2023, interestRate: 8.0, penaltyAmount: 12500 },
      { lienNumber: 'TL-2024-009', debtorName: 'Mountain View Developers', lienType: 'property', amount: 560000, status: 'active', propertyAddress: '1800 Hilltop Estates, Denver, CO', jurisdiction: 'Denver County', taxYear: 2022, interestRate: 15.0, penaltyAmount: 56000 },
      { lienNumber: 'TL-2024-010', debtorName: 'James & Maria Rodriguez', lienType: 'income', amount: 45000, status: 'expired', jurisdiction: 'IRS', taxYear: 2013, interestRate: 7.5, penaltyAmount: 4500 },
      { lienNumber: 'TL-2024-011', debtorName: 'Tech Innovations Inc', lienType: 'payroll', amount: 230000, status: 'active', propertyAddress: '400 Tech Blvd, San Jose, CA', jurisdiction: 'California EDD', taxYear: 2023, interestRate: 10.0, penaltyAmount: 23000 },
      { lienNumber: 'TL-2024-012', debtorName: 'Heritage Holdings Group', lienType: 'federal', amount: 890000, status: 'active', propertyAddress: '1500 Financial District, Dallas, TX', jurisdiction: 'IRS', taxYear: 2022, interestRate: 7.5, penaltyAmount: 89000 },
      { lienNumber: 'TL-2024-013', debtorName: 'Robert Anderson', lienType: 'property', amount: 18000, status: 'active', propertyAddress: '678 Maple St, Seattle, WA', jurisdiction: 'King County', taxYear: 2023, interestRate: 12.0, penaltyAmount: 1800 },
      { lienNumber: 'TL-2024-014', debtorName: 'Coastal Manufacturing', lienType: 'state', amount: 175000, status: 'paid', propertyAddress: '2200 Factory Lane, Charleston, SC', jurisdiction: 'South Carolina DOR', taxYear: 2022, interestRate: 9.0, penaltyAmount: 17500 },
      { lienNumber: 'TL-2024-015', debtorName: 'Global Trading Partners', lienType: 'federal', amount: 1250000, status: 'active', propertyAddress: '3000 Commerce Center, Los Angeles, CA', jurisdiction: 'IRS', taxYear: 2021, interestRate: 7.5, penaltyAmount: 125000 }
    ]);
    console.log('Tax Liens seeded');

    // Environmental Records (15)
    await EnvironmentalRecord.bulkCreate([
      { siteName: 'Former Acme Chemical Plant', address: '1200 Industrial Way, Newark, NJ', recordType: 'contamination', agency: 'EPA Region 2', status: 'remediation', contaminants: ['TCE', 'PCE', 'Benzene'], riskLevel: 'high', cleanupCost: 4500000, description: 'Superfund site with groundwater contamination', responsibleParty: 'Acme Chemical Corp' },
      { siteName: 'Riverside Gas Station', address: '456 River Road, Portland, OR', recordType: 'assessment', agency: 'Oregon DEQ', status: 'monitoring', contaminants: ['MTBE', 'Gasoline'], riskLevel: 'medium', cleanupCost: 250000, description: 'Underground storage tank leak assessment', responsibleParty: 'Quick Stop Fuels LLC' },
      { siteName: 'Mountain Mining Operations', address: '8900 Mine Road, Butte, MT', recordType: 'remediation', agency: 'EPA Region 8', status: 'remediation', contaminants: ['Arsenic', 'Lead', 'Mercury', 'Copper'], riskLevel: 'critical', cleanupCost: 85000000, description: 'Historic mining site with extensive heavy metal contamination', responsibleParty: 'Montana Mining Corp' },
      { siteName: 'Lakeside Power Plant', address: '300 Lakeshore Drive, Gary, IN', recordType: 'permit', agency: 'Indiana DEM', status: 'compliant', contaminants: ['SO2', 'NOx', 'Particulates'], riskLevel: 'medium', cleanupCost: 0, description: 'Air quality permit for coal-fired power plant', responsibleParty: 'Great Lakes Energy' },
      { siteName: 'Valley Electronics Facility', address: '567 Tech Park, San Jose, CA', recordType: 'contamination', agency: 'California DTSC', status: 'monitoring', contaminants: ['TCE', 'Chromium VI'], riskLevel: 'high', cleanupCost: 12000000, description: 'Solvent contamination from electronics manufacturing', responsibleParty: 'Valley Electronics Inc' },
      { siteName: 'Coastal Oil Terminal', address: '100 Harbor Blvd, Galveston, TX', recordType: 'violation', agency: 'EPA Region 6', status: 'open', contaminants: ['Crude Oil', 'Diesel'], riskLevel: 'high', cleanupCost: 3200000, description: 'Oil spill violation and wetland damage', responsibleParty: 'Gulf Coast Petroleum' },
      { siteName: 'Metro Dry Cleaners', address: '234 Main Street, Phoenix, AZ', recordType: 'assessment', agency: 'Arizona DEQ', status: 'closed', contaminants: ['PCE'], riskLevel: 'low', cleanupCost: 75000, description: 'Dry cleaning solvent contamination assessment', responsibleParty: 'Metro Cleaners LLC' },
      { siteName: 'Farmland Pesticide Storage', address: '5000 County Road 12, Fresno, CA', recordType: 'contamination', agency: 'California DTSC', status: 'remediation', contaminants: ['DDT', 'Chlordane', 'Dieldrin'], riskLevel: 'high', cleanupCost: 1800000, description: 'Legacy pesticide storage facility contamination', responsibleParty: 'Central Valley Agriculture' },
      { siteName: 'Abandoned Steel Mill', address: '7800 Mill Road, Pittsburgh, PA', recordType: 'remediation', agency: 'EPA Region 3', status: 'remediation', contaminants: ['Lead', 'Cadmium', 'PAHs', 'Asbestos'], riskLevel: 'critical', cleanupCost: 45000000, description: 'Brownfield redevelopment of former steel manufacturing site', responsibleParty: 'Pittsburgh Steel Legacy' },
      { siteName: 'Forest Products Facility', address: '900 Timber Lane, Eugene, OR', recordType: 'permit', agency: 'Oregon DEQ', status: 'compliant', contaminants: ['Wood Dust', 'Formaldehyde'], riskLevel: 'low', cleanupCost: 0, description: 'Air quality permit for lumber processing facility', responsibleParty: 'Pacific Lumber Co' },
      { siteName: 'Military Base Fuel Depot', address: '4200 Base Road, Norfolk, VA', recordType: 'contamination', agency: 'DoD Environmental', status: 'monitoring', contaminants: ['JP-8', 'PFAS', 'PFOA'], riskLevel: 'high', cleanupCost: 22000000, description: 'Military fuel storage contamination with PFAS chemicals', responsibleParty: 'U.S. Department of Defense' },
      { siteName: 'Chemical Distribution Center', address: '1600 Warehouse Row, Houston, TX', recordType: 'violation', agency: 'EPA Region 6', status: 'open', contaminants: ['Various Hazardous Materials'], riskLevel: 'critical', cleanupCost: 8500000, description: 'Chemical storage violations and improper waste disposal', responsibleParty: 'ChemDist Solutions' },
      { siteName: 'Auto Salvage Yard', address: '3400 Junkyard Road, Detroit, MI', recordType: 'assessment', agency: 'Michigan EGLE', status: 'monitoring', contaminants: ['Motor Oil', 'Lead', 'Antifreeze'], riskLevel: 'medium', cleanupCost: 450000, description: 'Soil and groundwater assessment at auto salvage facility', responsibleParty: 'Motor City Salvage' },
      { siteName: 'Textile Mill Complex', address: '200 Mill Street, Greenville, SC', recordType: 'remediation', agency: 'South Carolina DHEC', status: 'closed', contaminants: ['Dyes', 'Heavy Metals', 'Solvents'], riskLevel: 'medium', cleanupCost: 2100000, description: 'Completed remediation of historic textile manufacturing site', responsibleParty: 'Carolina Textile Heritage' },
      { siteName: 'Airport PFAS Site', address: '6000 Airport Road, Colorado Springs, CO', recordType: 'contamination', agency: 'Colorado DPHE', status: 'remediation', contaminants: ['PFAS', 'PFOA', 'PFOS'], riskLevel: 'high', cleanupCost: 35000000, description: 'AFFF firefighting foam contamination at military airport', responsibleParty: 'U.S. Air Force' }
    ]);
    console.log('Environmental Records seeded');

    // Campaign Finance (15)
    await CampaignFinance.bulkCreate([
      { committeeName: 'Citizens for Progress PAC', candidateName: 'Jennifer Roberts', office: 'U.S. Senate', party: 'Democratic', filingType: 'quarterly', amount: 2450000, donorName: 'Various', filingDate: new Date('2024-04-15'), electionCycle: '2024', reportingPeriod: 'Q1 2024', status: 'filed' },
      { committeeName: 'Freedom Works America', candidateName: 'Michael Thompson', office: 'U.S. House', party: 'Republican', filingType: 'contribution', amount: 5400, donorName: 'Robert Sterling', donorAddress: '100 Wall Street, New York, NY', filingDate: new Date('2024-03-01'), electionCycle: '2024', status: 'filed' },
      { committeeName: 'Tech Leaders Coalition', candidateName: 'Sarah Chen', office: 'Governor', party: 'Democratic', filingType: 'quarterly', amount: 8900000, donorName: 'Various', filingDate: new Date('2024-07-15'), electionCycle: '2024', reportingPeriod: 'Q2 2024', status: 'approved' },
      { committeeName: 'United for Healthcare Reform', candidateName: null, office: null, party: null, filingType: 'expenditure', amount: 1200000, filingDate: new Date('2024-05-20'), electionCycle: '2024', status: 'filed' },
      { committeeName: 'Johnson for Mayor Campaign', candidateName: 'David Johnson', office: 'Mayor', party: 'Independent', filingType: 'annual', amount: 450000, donorName: 'Various', filingDate: new Date('2024-01-31'), electionCycle: '2024', reportingPeriod: 'Annual 2023', status: 'approved' },
      { committeeName: 'National Business PAC', candidateName: null, office: null, party: 'Republican', filingType: 'quarterly', amount: 15600000, donorName: 'Various Corporate', filingDate: new Date('2024-10-15'), electionCycle: '2024', reportingPeriod: 'Q3 2024', status: 'filed' },
      { committeeName: 'Green Future Fund', candidateName: 'Emily Watson', office: 'State Senate', party: 'Green', filingType: 'contribution', amount: 2500, donorName: 'Sierra Environmental Group', donorAddress: '500 Earth Way, San Francisco, CA', filingDate: new Date('2024-06-01'), electionCycle: '2024', status: 'filed' },
      { committeeName: 'Workers First Committee', candidateName: 'Carlos Mendez', office: 'U.S. House', party: 'Democratic', filingType: 'quarterly', amount: 780000, donorName: 'Various Labor Unions', filingDate: new Date('2024-04-15'), electionCycle: '2024', reportingPeriod: 'Q1 2024', status: 'under_review' },
      { committeeName: 'Liberty Action Network', candidateName: 'Patricia Armstrong', office: 'U.S. Senate', party: 'Republican', filingType: 'amendment', amount: 3200000, filingDate: new Date('2024-08-30'), electionCycle: '2024', status: 'amended' },
      { committeeName: 'Community Voices Coalition', candidateName: 'James Lee', office: 'City Council', party: 'Democratic', filingType: 'annual', amount: 125000, donorName: 'Various Individual', filingDate: new Date('2024-01-31'), electionCycle: '2024', reportingPeriod: 'Annual 2023', status: 'approved' },
      { committeeName: 'Reform Now Super PAC', candidateName: null, office: null, party: null, filingType: 'expenditure', amount: 8500000, filingDate: new Date('2024-09-15'), electionCycle: '2024', status: 'flagged' },
      { committeeName: 'Veterans Leadership PAC', candidateName: 'Col. Robert Davis (Ret.)', office: 'U.S. House', party: 'Republican', filingType: 'quarterly', amount: 920000, donorName: 'Various Veterans Groups', filingDate: new Date('2024-07-15'), electionCycle: '2024', reportingPeriod: 'Q2 2024', status: 'filed' },
      { committeeName: 'Education First Alliance', candidateName: 'Amanda Foster', office: 'School Board', party: 'Non-Partisan', filingType: 'contribution', amount: 15000, donorName: 'Teachers Union Local 47', donorAddress: '300 Education Blvd, Denver, CO', filingDate: new Date('2024-02-15'), electionCycle: '2024', status: 'filed' },
      { committeeName: 'Small Business Owners PAC', candidateName: null, office: null, party: 'Republican', filingType: 'quarterly', amount: 2800000, donorName: 'Various Small Business', filingDate: new Date('2024-10-15'), electionCycle: '2024', reportingPeriod: 'Q3 2024', status: 'approved' },
      { committeeName: 'Clean Energy Action Fund', candidateName: 'Rachel Kim', office: 'State Representative', party: 'Democratic', filingType: 'quarterly', amount: 340000, donorName: 'Various Environmental', filingDate: new Date('2024-04-15'), electionCycle: '2024', reportingPeriod: 'Q1 2024', status: 'filed' }
    ]);
    console.log('Campaign Finance seeded');

    // Professional Licenses (15)
    await ProfessionalLicense.bulkCreate([
      { licenseNumber: 'MD-2024-001234', licenseType: 'Medical Doctor', holderName: 'Dr. Sarah Mitchell', profession: 'Physician - Internal Medicine', issuingAuthority: 'State Medical Board', state: 'CA', issueDate: '2020-06-15', expirationDate: '2026-06-15', status: 'active', specializations: ['Internal Medicine', 'Geriatrics'] },
      { licenseNumber: 'BAR-2024-005678', licenseType: 'Attorney at Law', holderName: 'James O\'Connor', profession: 'Attorney', issuingAuthority: 'State Bar Association', state: 'NY', issueDate: '2018-11-01', expirationDate: '2025-11-01', status: 'active', specializations: ['Corporate Law', 'M&A'] },
      { licenseNumber: 'PE-2024-002345', licenseType: 'Professional Engineer', holderName: 'Maria Rodriguez', profession: 'Civil Engineer', issuingAuthority: 'Board of Professional Engineers', state: 'TX', issueDate: '2019-03-20', expirationDate: '2025-03-20', status: 'pending_renewal', specializations: ['Structural Engineering'] },
      { licenseNumber: 'CPA-2024-003456', licenseType: 'Certified Public Accountant', holderName: 'David Kim', profession: 'Accountant', issuingAuthority: 'Board of Accountancy', state: 'IL', issueDate: '2021-01-10', expirationDate: '2027-01-10', status: 'active', specializations: ['Tax', 'Audit'] },
      { licenseNumber: 'RN-2024-004567', licenseType: 'Registered Nurse', holderName: 'Emily Watson', profession: 'Nurse Practitioner', issuingAuthority: 'Board of Nursing', state: 'FL', issueDate: '2022-05-15', expirationDate: '2026-05-15', status: 'active', specializations: ['Pediatrics', 'Critical Care'] },
      { licenseNumber: 'RE-2024-006789', licenseType: 'Real Estate Broker', holderName: 'Thomas Wright', profession: 'Real Estate Broker', issuingAuthority: 'Real Estate Commission', state: 'CA', issueDate: '2020-09-01', expirationDate: '2024-09-01', status: 'expired', specializations: ['Commercial', 'Residential'] },
      { licenseNumber: 'DDS-2024-007890', licenseType: 'Doctor of Dental Surgery', holderName: 'Dr. Lisa Park', profession: 'Dentist', issuingAuthority: 'Dental Board', state: 'WA', issueDate: '2019-07-20', expirationDate: '2025-07-20', status: 'active', specializations: ['Orthodontics', 'Cosmetic Dentistry'] },
      { licenseNumber: 'ARC-2024-008901', licenseType: 'Architect', holderName: 'Robert Chen', profession: 'Architect', issuingAuthority: 'Board of Architecture', state: 'NY', issueDate: '2017-12-01', expirationDate: '2025-12-01', status: 'active', specializations: ['Sustainable Design', 'Urban Planning'] },
      { licenseNumber: 'PHM-2024-009012', licenseType: 'Pharmacist', holderName: 'Amanda Foster', profession: 'Pharmacist', issuingAuthority: 'Board of Pharmacy', state: 'PA', issueDate: '2021-08-15', expirationDate: '2025-08-15', status: 'active', specializations: ['Clinical Pharmacy'] },
      { licenseNumber: 'PSY-2024-010123', licenseType: 'Licensed Psychologist', holderName: 'Dr. Karen White', profession: 'Clinical Psychologist', issuingAuthority: 'Board of Psychology', state: 'CO', issueDate: '2018-04-01', expirationDate: '2024-04-01', status: 'suspended', disciplinaryActions: [{ date: '2024-02-15', action: 'License suspended pending investigation' }] },
      { licenseNumber: 'GC-2024-011234', licenseType: 'General Contractor', holderName: 'Michael Brown', profession: 'General Contractor', issuingAuthority: 'Contractors State License Board', state: 'CA', issueDate: '2016-06-01', expirationDate: '2026-06-01', status: 'active', specializations: ['Residential', 'Commercial'] },
      { licenseNumber: 'INS-2024-012345', licenseType: 'Insurance Agent', holderName: 'Patricia Davis', profession: 'Insurance Agent', issuingAuthority: 'Department of Insurance', state: 'GA', issueDate: '2022-02-01', expirationDate: '2026-02-01', status: 'active', specializations: ['Life', 'Health', 'Property'] },
      { licenseNumber: 'VET-2024-013456', licenseType: 'Veterinarian', holderName: 'Dr. Carlos Mendez', profession: 'Veterinarian', issuingAuthority: 'Board of Veterinary Medicine', state: 'OR', issueDate: '2020-10-15', expirationDate: '2026-10-15', status: 'active', specializations: ['Small Animal', 'Surgery'] },
      { licenseNumber: 'PLB-2024-014567', licenseType: 'Master Plumber', holderName: 'Kevin O\'Brien', profession: 'Plumber', issuingAuthority: 'Plumbing Board', state: 'MA', issueDate: '2015-03-01', expirationDate: '2025-03-01', status: 'active', specializations: ['Commercial', 'Gas Fitting'] },
      { licenseNumber: 'CFP-2024-015678', licenseType: 'Certified Financial Planner', holderName: 'Jennifer Adams', profession: 'Financial Planner', issuingAuthority: 'CFP Board', state: 'AZ', issueDate: '2019-11-01', expirationDate: '2025-11-01', status: 'active', specializations: ['Retirement Planning', 'Estate Planning'] }
    ]);
    console.log('Professional Licenses seeded');

    // Government Contracts (15)
    await GovernmentContract.bulkCreate([
      { contractNumber: 'GC-2024-FA-001', title: 'F-35 Maintenance Support Services', agency: 'Department of Defense', vendorName: 'Lockheed Martin Corp', contractValue: 450000000, startDate: '2024-01-15', endDate: '2029-01-14', status: 'active', contractType: 'cost_plus', description: 'Maintenance and logistics support for F-35 fighter fleet', naicsCode: '336411', placeOfPerformance: 'Fort Worth, TX' },
      { contractNumber: 'GC-2024-IT-002', title: 'Cloud Infrastructure Modernization', agency: 'Department of Veterans Affairs', vendorName: 'Amazon Web Services', contractValue: 125000000, startDate: '2024-03-01', endDate: '2027-02-28', status: 'active', contractType: 'fixed_price', description: 'Migration of VA healthcare systems to cloud infrastructure', naicsCode: '541512', placeOfPerformance: 'Washington, DC' },
      { contractNumber: 'GC-2024-HW-003', title: 'Interstate Highway Bridge Repair', agency: 'Department of Transportation', vendorName: 'Granite Construction', contractValue: 78000000, startDate: '2024-04-15', endDate: '2026-10-14', status: 'active', contractType: 'fixed_price', description: 'Repair and rehabilitation of 45 interstate highway bridges', naicsCode: '237310', placeOfPerformance: 'Multiple States' },
      { contractNumber: 'GC-2024-MED-004', title: 'Medical Supplies Distribution', agency: 'Health and Human Services', vendorName: 'McKesson Corporation', contractValue: 890000000, startDate: '2024-01-01', endDate: '2028-12-31', status: 'active', contractType: 'indefinite_delivery', description: 'Strategic national stockpile medical supply distribution', naicsCode: '424210', placeOfPerformance: 'Nationwide' },
      { contractNumber: 'GC-2024-SEC-005', title: 'Cybersecurity Operations Center', agency: 'Department of Homeland Security', vendorName: 'Booz Allen Hamilton', contractValue: 250000000, startDate: '2024-06-01', endDate: '2029-05-31', status: 'active', contractType: 'time_materials', description: '24/7 cybersecurity monitoring and incident response', naicsCode: '541519', placeOfPerformance: 'Arlington, VA' },
      { contractNumber: 'GC-2024-SP-006', title: 'Space Launch Services', agency: 'NASA', vendorName: 'SpaceX', contractValue: 3200000000, startDate: '2024-02-01', endDate: '2030-01-31', status: 'active', contractType: 'fixed_price', description: 'Commercial crew and cargo transportation to ISS', naicsCode: '336414', placeOfPerformance: 'Cape Canaveral, FL' },
      { contractNumber: 'GC-2024-ENV-007', title: 'Superfund Site Remediation', agency: 'Environmental Protection Agency', vendorName: 'Arcadis Environmental', contractValue: 45000000, startDate: '2024-05-01', endDate: '2027-04-30', status: 'active', contractType: 'cost_plus', description: 'Remediation services for 12 Superfund priority sites', naicsCode: '562910', placeOfPerformance: 'Multiple States' },
      { contractNumber: 'GC-2024-ED-008', title: 'Student Loan Servicing Platform', agency: 'Department of Education', vendorName: 'Accenture Federal', contractValue: 180000000, startDate: '2024-07-01', endDate: '2029-06-30', status: 'pending', contractType: 'fixed_price', description: 'Next generation student loan servicing and management platform', naicsCode: '541511', placeOfPerformance: 'Washington, DC' },
      { contractNumber: 'GC-2024-AG-009', title: 'Agricultural Research Services', agency: 'Department of Agriculture', vendorName: 'Battelle Memorial Institute', contractValue: 65000000, startDate: '2024-03-15', endDate: '2027-03-14', status: 'active', contractType: 'cost_plus', description: 'Research on crop resilience and sustainable farming practices', naicsCode: '541711', placeOfPerformance: 'Beltsville, MD' },
      { contractNumber: 'GC-2024-EN-010', title: 'Nuclear Facility Decommissioning', agency: 'Department of Energy', vendorName: 'Bechtel National', contractValue: 2100000000, startDate: '2024-01-01', endDate: '2034-12-31', status: 'active', contractType: 'cost_plus', description: 'Decommissioning and cleanup of former nuclear weapons facility', naicsCode: '562211', placeOfPerformance: 'Hanford, WA' },
      { contractNumber: 'GC-2024-JUS-011', title: 'Federal Prison Facilities Management', agency: 'Department of Justice', vendorName: 'GEO Group', contractValue: 340000000, startDate: '2024-04-01', endDate: '2029-03-31', status: 'active', contractType: 'fixed_price', description: 'Management and operation of federal correctional facilities', naicsCode: '922140', placeOfPerformance: 'Multiple States' },
      { contractNumber: 'GC-2024-INT-012', title: 'National Park Infrastructure', agency: 'Department of Interior', vendorName: 'Turner Construction', contractValue: 92000000, startDate: '2024-05-15', endDate: '2027-05-14', status: 'awarded', contractType: 'fixed_price', description: 'Visitor center construction and trail improvements in national parks', naicsCode: '236220', placeOfPerformance: 'Multiple Parks' },
      { contractNumber: 'GC-2024-COM-013', title: 'Weather Satellite Systems', agency: 'NOAA', vendorName: 'Northrop Grumman', contractValue: 1800000000, startDate: '2024-02-15', endDate: '2032-02-14', status: 'active', contractType: 'cost_plus', description: 'Next generation weather observation satellite development and launch', naicsCode: '334511', placeOfPerformance: 'Redondo Beach, CA' },
      { contractNumber: 'GC-2024-SBA-014', title: 'Small Business IT Support', agency: 'Small Business Administration', vendorName: 'Leidos', contractValue: 35000000, startDate: '2024-08-01', endDate: '2027-07-31', status: 'active', contractType: 'blanket', description: 'IT infrastructure support and modernization for SBA systems', naicsCode: '541513', setAside: '8(a)', placeOfPerformance: 'Washington, DC' },
      { contractNumber: 'GC-2024-ST-015', title: 'Embassy Security Systems', agency: 'Department of State', vendorName: 'L3Harris Technologies', contractValue: 420000000, startDate: '2024-01-01', endDate: '2029-12-31', status: 'active', contractType: 'indefinite_delivery', description: 'Physical and electronic security systems for US embassies worldwide', naicsCode: '561612', placeOfPerformance: 'Worldwide' }
    ]);
    console.log('Government Contracts seeded');

    console.log('\n✅ All data seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}

seed();
